#include <stdint.h>
#include <string.h>

#include <sgx_tseal.h>
#include <sgx_utils.h>

#include "enclave_t.h" // auto-generated by edger8

#include "libnexus_trusted/nexus_log.h"
#include "libnexus_trusted/nexus_util.h"


static int
__copy_to_untrusted(void * trusted_ptr, size_t len, uint8_t ** untrusted_ptr)
{
    int       err       = -1;
    uint8_t * ocall_ptr = NULL;

    err = ocall_calloc((void **)&ocall_ptr, len);

    if (err || ocall_ptr == NULL) {
        log_error("allocation failed. err=%x, untrusted_ptr=%p\n", err, ocall_ptr);
        return -1;
    }

    memcpy(ocall_ptr, trusted_ptr, len);

    *untrusted_ptr = ocall_ptr;

    return 0;
}

static void
__copy_from_untrusted(void * untrusted_ptr, size_t len, uint8_t ** trusted_ptr)
{
    uint8_t * _result = nexus_malloc(len);

    memcpy(_result, untrusted_ptr, len);

    *trusted_ptr = _result;
}



uint8_t *
seal_data(uint8_t * data, size_t size, size_t * p_sealed_len)
{
    size_t              sealed_len  = sgx_calc_sealed_data_size(0, size);

    sgx_sealed_data_t * sealed_data = nexus_malloc(sealed_len);

    {
        int ret = sgx_seal_data(0, NULL, size, data, sealed_len, sealed_data);

        if (ret != 0) {
            nexus_free(sealed_data);
            log_error("sgx_seal_data() FAILED (ret=%x)\n", ret);
            return NULL;
        }
    }

    *p_sealed_len = sealed_len;

    return (uint8_t *)sealed_data;
}


uint8_t *
unseal_data(uint8_t * data, size_t size, size_t * p_unsealed_len)
{
    sgx_sealed_data_t * sealed_data   = (sgx_sealed_data_t *)data;

    uint32_t            unsealed_len  = sgx_get_encrypt_txt_len(sealed_data);

    uint8_t           * unsealed_data = nexus_malloc(unsealed_len);

    {
        int ret = sgx_unseal_data(sealed_data, NULL, 0, unsealed_data, &unsealed_len);

        if (ret != 0) {
            nexus_free(unsealed_data);
            log_error("sgx_unseal_data FAILED (ret=%x)\n", ret);
            return NULL;
        }
    }

    *p_unsealed_len = unsealed_len;

    return (uint8_t *)unsealed_data;
}


char *
ecall_unseal_data(uint8_t * input_buffer_in, size_t input_buffer_len, size_t * output_len_out)
{
    char    * unsealed_data    = NULL;

    size_t    unsealed_len     = 0;

    uint8_t * trusted_buffer   = NULL;

    char    * untrusted_output = NULL;


    __copy_from_untrusted(input_buffer_in, input_buffer_len, &trusted_buffer);

    unsealed_data = unseal_data(trusted_buffer, input_buffer_len, &unsealed_len);

    if (unsealed_data == NULL) {
        log_error("could not seal data\n");
        goto err;
    }

    if (__copy_to_untrusted(unsealed_data, unsealed_len, (uint8_t **)&untrusted_output)) {
        nexus_free(unsealed_data);

        log_error("__copy_to_untrusted FAILED\n");
        goto err;
    }

    nexus_free(unsealed_data);
    nexus_free(trusted_buffer);

    *output_len_out = unsealed_len;

    return untrusted_output;
err:
    nexus_free(trusted_buffer);

    return NULL;
}


uint8_t *
ecall_seal_data(char * input_buffer_IN, size_t input_buffer_len, size_t * output_len_out)
{
    uint8_t * sealed_data      = NULL;

    size_t    sealed_data_len  = 0;

    uint8_t * trusted_buffer   = NULL;

    uint8_t * untrusted_output = NULL;


    __copy_from_untrusted(input_buffer_IN, input_buffer_len, &trusted_buffer);

    sealed_data = seal_data(trusted_buffer, input_buffer_len, &sealed_data_len);

    if (sealed_data == NULL) {
        log_error("could not seal data\n");
        goto err;
    }

    if (__copy_to_untrusted(sealed_data, sealed_data_len, &untrusted_output)) {
        nexus_free(sealed_data);

        log_error("__copy_to_untrusted FAILED\n");
        goto err;
    }

    nexus_free(sealed_data);
    nexus_free(trusted_buffer);

    *output_len_out = sealed_data_len;

    return untrusted_output;
err:
    nexus_free(trusted_buffer);

    return NULL;
}
