#include <stdint.h>
#include <string.h>

#include "enclave_t.h" // auto-generated by edger8

static const char hello_world_str[] = "hello world";

int
ecall_hello_world(char * buffer_out)
{
    memcpy(buffer_out, hello_world_str, strlen(hello_world_str));

    return 0;
}
